[window]
dynamic_padding = true
decorations = "None"
opacity = 0.9
blur = true
# padding = { x = 5, y = 5 }

[font]
normal = { family = "Iosevka Nerd Font", style = "Regular" }
size = 12.0

[terminal]
osc52 = "CopyPaste"

[cursor]
style = { shape = "Beam", blinking = "Off" }
